### ISSUE TITLE
Support fixed precision OverlayNG functions

### ISSUE THREAD

**Issue by sgillies** [shapely/shapely#1055]
The OverlayNG API in GEOS 3.9 adds `*Prec` functions which take a `double gridSize` argument.

```cpp
    Geometry*
    GEOSDifference_r(GEOSContextHandle_t extHandle, const Geometry* g1, const Geometry* g2)
    {
        return execute(extHandle, [&]() {
            auto g3 = g1->difference(g2);
            g3->setSRID(g1->getSRID());
            return g3.release();
        });
    }

    Geometry*
    GEOSDifferencePrec_r(GEOSContextHandle_t extHandle, const Geometry* g1, const Geometry* g2, double gridSize)
    {
        return execute(extHandle, [&]() {

            std::unique_ptr<PrecisionModel> pm;
            if(gridSize != 0) {
                pm.reset(new PrecisionModel(1.0 / gridSize));
            }
            else {
                pm.reset(new PrecisionModel());
            }
            auto g3 = gridSize != 0 ?
                OverlayNG::overlay(g1, g2, OverlayNG::DIFFERENCE, pm.get())
                :
                OverlayNGRobust::Overlay(g1, g2, OverlayNG::DIFFERENCE);
            g3->setSRID(g1->getSRID());
            return g3.release();
        });
    }
```

Shapely 1.8.0 could add an optional `grid_size` (name to be decided) keyword argument to geometry methods like `.difference()` and if it's nonzero, call `GEOSDifferencePrec_r` it is is available. And if it isn't, warn or raise.

**Comment by tomplex** [comment]
I'd love to be able to take advantage of this improvement in GEOS. I've been busy with life lately but I would be happy to try to get something started for this.

In terms of behavior, I'd probably be heavy-handed and raise if the user is trying to specify a precision and the functionality is not available.

**Comment by jorisvandenbossche** [comment]
It will indeed be nice to add precision support to Shapely. 
(to clarify some terminology, general OverlayNG support we get automatically once building against GEOS 3.9, since also all overlay operations use the improved OverlayNG implementation by default. It's only the additional features enabled by OverlayNG to specify precision for overlay operations that needs work to expose)

@brendan-ward started to work on this in pygeos at https://github.com/pygeos/pygeos/pull/257. Feedback on that PR is very welcome!

Personally, I would argue that we shouldn't try to add this to Shapely 1.8, but directly do this in the shapely-2.0 branch. 
(the shapely-2.0 branch has almost completely removed the ctypes-based GEOS bindings, so any addition in the master branch will basically directly be removed in the shapely-2.0 branch. So therefore, IMO, major work on the ctypes bindings in master is not worth it at the moment)

**Comment by mwtoews** [comment]
Thanks @sgillies for kicking this discussion off. I was about to, but my spare time has evaporated for the past month with a newborn (and toddler).

The five new OverlayNG functions with GEOS 3.9 that have a `gridSize` parameter are:
* GEOSIntersectionPrec
* GEOSDifferencePrec
* GEOSSymDifferencePrec
* GEOSUnionPrec
* GEOSUnaryUnionPrec

Yes, I agree that `grid_size` is an appropriate parameter name for these functions, with a default of 0 for FLOATING precision.

@jorisvandenbossche the feature you are describing (get/set precision) predates OverlayNG, and has been around since GEOS 3.6.0 (2016-10-25). This feature has not been implemented in shapely, but is discussed in #110

As to whether this could be a shapely 1.8 feature (or not), I think this could be added to the ctypes implementation for 1.8. It should throw an exception if `grid_size != 0` with an older GEOS version.

**Comment by jorisvandenbossche** [comment]
Ah yes, sorry, I was swapping those two features (and missed that it was explicitly about the `*prec` functions in the top post. That's what you get from answering too fast without reading properly ..).  
(the main point I tried to make that the improved OverlayNG functions are already used automatically when building against GEOS 3.9 since they are the default still stands though ;), I renamed the title of the issue slightly to reduce the confusion) 

Now, in the meantime, @brendan-ward *also* already did a PR to add the fixed precision overlay functions in https://github.com/pygeos/pygeos/pull/276, and added the `grid_size` keyword as suggested here.

> As to whether this could be a shapely 1.8 feature (or not), I think this could be added to the ctypes implementation for 1.8. It should throw an exception if grid_size != 0 with an older GEOS version.

To be clear, it *can* certainly be added to shapely 1.8. But we all have limited time, so my main worry is that it would only delay the 1.8/2.0 released further.

**Comment by sgillies** [comment]
Let's save this for 2.0. 1.8 doesn't have much of a mission other than to warn of upcoming changes in 2.0. I'd prefer we didn't add any features in 1.8.0.

**Comment by jorisvandenbossche** [comment]
As mentioned above, this was added in pygeos through a `grid_size` keyword in the overlay operations (`union`, `intersection`, etc). Now this code is moved into Shapely, this feature is already done here as well. 

Therefore, closing this issue. 

(we should keep track of all new features for Shapely 2.0 though (as many things have been implicitly added with the pygeos merge), so we can properly document this in the release notes; will open a separate issue for this)
