### ISSUE TITLE
Drop Python 3.6 supported (end of life Dec 2021)

### ISSUE THREAD

**Issue by EwoutH** [shapely/shapely#1205]
The security-only support for Python 3.6 ends in Dec 2021, after Python 3.6 will be end-of-life (see [PEP 494](https://www.python.org/dev/peps/pep-0494/)). With 1.8 released as a stable version supporting Python 3.6, would it be time to drop Python 3.6 support, looking forward to the Shapely 2.0 release? Especially as Python 3.10 support is ramped up.

**Comment by mwtoews** [comment]
I'm in two minds on when to drop Python 3.6 support, similar to @caspervdw's [comment](https://github.com/pygeos/pygeos/issues/414#issuecomment-954986554). On one end, I'd like to see a smaller CI footprint and would like to align the project closer to [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html) (although NumPy is py38+). But on the other end, there is not much extra burden in maintaining older Python3 compatibility. Lots of folks, including myself, are still using Ubuntu 18.04 (with EOL April 2023), which natively supports Python 3.6, NumPy 1.13 and GEOS 3.6.

Any other thoughts on this? Does anyone plan to use shapely-2.0 with Python 3.6 for at least another year? Are there any planned development features that can only be implemented with Python 3.7 or later?

**Comment by jorisvandenbossche** [comment]
I don't think we have much maintenance burden in supporting Python 3.6 for now (I don't recall an issue or difficulty while contributing related to this recently). So from that point of view, I don't feel strongly about dropping support sooner rather than later. And if there are people (even from the core team) still using it, that seems as a good reason to keep it for now.

I think we will mostly "miss out" on new features by keeping older Python support. But with Python 3.6 we eg already have f-strings and ordered dicts. And I don't directly see features in Pyton 3.7 I would really miss (we don't yet use type annotations anyway, and I don't think we have use for dataclasses)

**Comment by mwtoews** [comment]
PR #1426 to move static project metadata to `pyproject.toml` ([PEP 621](https://peps.python.org/pep-0621/)) is blocked by Python 3.6 (because setuptools 61+ support starts from Python 3.7). This seems like a good reason to drop Python 3.6 for Shapely 2.0.
