### ISSUE TITLE
arm build wheel for apple m1

### ISSUE THREAD

**Issue by DeoLeung** [shapely/shapely#1325]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.

expect to install the wheel of `shapely==1.8.1`

currently it downloads the source and build locally, which will be missing the `libgeos`

## Steps to reproduce the problem.

* on mac m1 using docker client
```bash
docker run --rm -it python:3.9.10-slim pip install shapely==1.8.1
Collecting shapely==1.8.1
  Downloading Shapely-1.8.1.tar.gz (278 kB)
```

## Operating system

mac m1

## Shapely version and provenance

1.8.1 and 1.8.1.post1

**Comment by Rikuoja** [comment]
Encountered the same.

Weird, since looks like the tests build it correctly, but it doesn't build with docker.

**Comment by jorisvandenbossche** [comment]
Such manylinux aarch64 wheels were build for Shapely 1.8.0, so a temporary solution is to either 1) pin to 1.8.0, or 2) to ensure you have GEOS installed in the docker container before pip installing Shapely.

The reason for not having aarch64 wheels at the moment is because those are build on Travis, which is currently disabled for shapely due to their new OSS policy ("negative credit balance")

**Comment by johnthagen** [comment]
I wonder if a QEMU solution would work for Shapely: https://github.com/uraimo/run-on-arch-action

**Comment by jorisvandenbossche** [comment]
We tried that before (using the `docker/setup-qemu-action` action), it worked but we stopped using it because it took a very long time (for pygeos, but the wheel building infrastructure has now been copied exactly into Shapely): see https://github.com/pygeos/pygeos/issues/442

For the main branch, we have Travis set up again, so as long as that keeps working, that seems like a good alternative (although having everything in a single workflow in github actions would of course be easier to maintain)

**Comment by johnthagen** [comment]
@jorisvandenbossche That sounds great. Definitely understand the maintenance burden that comes with multiple CI systems, and the unfortunate pain caused by Travis back-peddling their "free for open source forever" statement.

Hopefully GitHub Actions/Azure will have an ARM solution soon.

Thanks!
