### ISSUE TITLE
pyproj deprecation warning in shapely.ops transform function

### ISSUE THREAD

**Issue by PHoltzmanMaxar** [shapely/shapely#1328]
## Expected behavior and actual behavior.

I'm getting this warning when using the transform function from shapely.ops
/env/lib/python3.8/site-packages/shapely/ops.py:305: DeprecationWarning: This function is deprecated. See: https://pyproj4.github.io/pyproj/stable/gotchas.html#upgrading-to-pyproj-2-from-pyproj-1
  zip(*func(*zip(*geom.exterior.coords))))

## Code Snippet

```
area_geom = transform(
                partial(
                    pyproj.transform,
                    pyproj.Proj(init='EPSG:4326'),
                    pyproj.Proj(
                        proj='aea',  # Albers equal area
                        lat_1=wgs84_geom.bounds[1],
                        lat_2=wgs84_geom.bounds[3]
                    )
                ),
                wgs84_geom
            )
```

## Operating system
centos7

## Shapely version and provenance
python 3.8.5
shapely==1.8.1.post1 installed from PyPI using pip

**Comment by jorisvandenbossche** [comment]
@PHoltzmanMaxar the `shapely.ops` module is itself not using pyproj, so I suppose you are passing a pyproj function to `transform`?

**Comment by PHoltzmanMaxar** [comment]
Yes, I am, and I'm struggling to wrap my head around 2 different warnings and what to do about them. 1 is as listed above. The other relates to using "init" with pyproj. I've edited my issue above to include the code snippet.

**Comment by jorisvandenbossche** [comment]
That are both warnings coming from pyproj, so unrelated to Shapely (therefore I am going to close this issue)

For the one warning, you already found the link (in the warning message) about how to solve this: https://github.com/OSGeo/gdal/issues/3060 (use the `Transformer` object instead of the `transform` function). 

For the second warning, you now need to use `pyproj.CRS` instead of `pyproj.Proj` and without using `init` keyword. See https://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code

The Shapely docs include a full example of using `shapely.ops.transform` with pyproj, and it shows the code both in the "old" way (for pyproj 1) and the new way: https://shapely.readthedocs.io/en/latest/manual.html#other-transformations
