### ISSUE TITLE
ops.unary_union changed behavior from 1.8 to 2.0 when given an empty list, and now returns None

### ISSUE THREAD

**Issue by Lyle-Alloy** [shapely/shapely#1332]
I'm not sure what the expected behavior is here, but I feel that always returning a shapely geometry is the safest as it means that the user doesn't always need to validate parameters/returns.

I found this by running the test suite for our project that uses shapely. We end up with quite a bit of strange/organic (and sometimes invalid!) geometry from user data so I have definitely found some edge cases (will be making more issues!).

### Expected (1.8)

```python
>>> from shapely import ops
>>> print(ops.unary_union([]))
GEOMETRYCOLLECTION EMPTY
```

### Actual (2.0)

```python
>>> from shapely import ops
>>> print(ops.unary_union([]))
None
```

## Steps to reproduce the problem.

```python
from shapely import ops
assert ops.unary_union([]) is not None
```

## Operating system

MacOS Catalina

```
Python 3.9.2 (default, Feb 28 2022, 13:37:28)
[Clang 12.0.0 (clang-1200.0.32.29)]
```

## Shapely version and provenance

Installed using `python setup.py develop` for both versions

**Comment by Lyle-Alloy** [comment]
I'm discovering some odd behavior with some of the other set functions that isn't quite intuitive:
```python
>>> print(set_operations.intersection_all([geometry.base.EmptyGeometry(), None]))
None
>>> print(set_operations.intersection_all([geometry.base.EmptyGeometry(), geometry.base.EmptyGeometry(), None]))
GEOMETRYCOLLECTION EMPTY
```

I guess it's more of a design question, but should these functions even be capable of handling `None`? It seems like the shapely/pygeos equivalent of `None` is `GEOMETRYCOLLECTION EMPTY`. One possible solution would be to maybe coerce `None` values to `GEOMETRYCOLLECTION EMPTY` on input. 

Alternatively maybe it could coerce the return to `GEOMETRYCOLLECTION EMPTY` instead of `None`. That would put it more in line with constructing a collection from 0, 1, or 1+ `None` values:

```python
>>> print(geometry.GeometryCollection([]))
GEOMETRYCOLLECTION EMPTY
>>> print(geometry.GeometryCollection([None]))
GEOMETRYCOLLECTION EMPTY
>>> print(geometry.GeometryCollection([None, None]))
GEOMETRYCOLLECTION EMPTY
```

Very excited to see all of the progress on Shapely 2.0! It really seems like you're down to more of the fine tuning, let me know if there's any good entry level tickets I could maybe take a stab at

**Comment by jorisvandenbossche** [comment]
We discussed this yesterday and were thinking to restore the behaviour of `unary_union`: currently we are special casing `union_all`/`unary_union` to return None instead of en empty collection. But instead, we could remove that special case and rather add a check to `intersection_all`/`symmetric_difference_all`/`coverage_union_all` to return an empty collection if the result would be None.

Thinking a bit further about it, we could mimic the [`np.ufunc.reduce`](https://numpy.org/doc/stable/reference/generated/numpy.ufunc.reduce.html) interface, and add an `initial` keyword to allow the user to control which value to return in case of an empty (or all-None) input array.  
That would certainly be an advanced feature (and so we should give a could default so most people don't have to care about this), but I can think of some use cases where this could be useful. For example, if you would want to an `intersection_all` on a big array in parallel in a tree-like fashion: first calculate the intersection for separate parts of the array, and then a final reduction step doing the intersection_all of all results. In such a case, you don't want an accidental empty to occur in case one array part would only contain missing values.

cc @brendan-ward

**Comment by brendan-ward** [comment]
I've been working on this; it is an easy fix when the `axis` is the default of `0` and proving to be more awkward when `axis` >= 1.

However, it seems like we want the all-empty case to be handled as it is now, which generally uses the correct geometry type based on the inputs, e.g.,

```Python
>>> shapely.union_all([shapely.Point(), shapely.Point()])
<POINT EMPTY>
```

Note that for `coverage_union_all` the result would be an empty MultiPolygon, since that function only applies to Polygon inputs.

I like the idea of using a parameter to control what should be returned from the reduce operation when `None` would otherwise be returned, but I don't know that we want to use the `initial` keyword specifically here to avoid implication from what the ufuncs do.  E.g., I wouldn't want the value passed in to actually be used as the starting point of the reduction in the case of intersection.

This parameter would be nice in that you could use it to keep your geometry types consistent; e.g., if the function returns Point types for non-None results, an empty point is a good value.  I wonder if the parameter should be the type of the geometry to return instead of an instance of that type, e.g., `if_none="Point"` rather than `if_none=Point()`.  That is, instead of allowing passing of a scalar type, to pass something we use internally to construct the scalar type.

**Comment by caspervdw** [comment]
I gave this issue some more thought. 

**EMPTY vs None vs NaN**

There is a fundamental difference between EMPTY and None. EMPTY has a clear mathematical definition: an empty set. The intersection of a geometry with an empty is an empty geometry. No doubt about that. 

On the other hand, None means: a missing value. It can have a lot of different use cases, sometimes meaning "we don't know what the value is", and sometimes "there is no value". Depending on the context, operations (like intersections) are expected to behave differently. See for instance https://pandas.pydata.org/docs/user_guide/missing_data.html for more info.

For performance reasons, we use NaN for missing float values. This is because NaN is of type `float`. Basically to us, a NaN is the `float` equivalent of `None`.

Integers and bools don't have this option. Any predicate on a NaN or None returns False.

**Comparison to numpy**

Numpy has many reduction operations. These operations return NaN if any input is NaN. For example:

```
In [1]: import numpy as np
In [2]: np.mean([1.0, np.nan, 2.0])
Out[2]: nan
In [3]: np.sum([1.0, np.nan, 2.0])
Out[3]: nan
```

Most (each?) of these has a version that skips NaN:

```
In [4]: np.nanmean([1.0, np.nan, 2.0])
Out[4]: 1.5
In [5]: np.nansum([1.0, np.nan, 2.0])
Out[5]: 3.0
```

The behaviour on all-NaN arrays differs per function:

```
In [6]: np.nanmean([np.nan, np.nan, np.nan])
<ipython-input-6-fc786a25e531>:1: RuntimeWarning: Mean of empty slice
  np.nanmean([np.nan, np.nan, np.nan])
Out[6]: nan
In [7]: np.nansum([np.nan, np.nan, np.nan])
Out[7]: 0.0
```

And is the same for the "normal" version on an empty array:

```
In [9]: np.mean([])
/home/casper/code/shapely/.venv/lib/python3.10/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/casper/code/shapely/.venv/lib/python3.10/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Out[9]: nan
In [10]: np.sum([])
Out[10]: 0.0
```

**Comparison to pandas**

Pandas has the same functionality, but exposed differently to the user. For `DataFrame.sum`, there is no `DataFrame.nansum`. Instead the behaviour is controlled with the kwarg `skipna` (see https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.sum.html#pandas-dataframe-sum)

There are basically two separate issues here, both with options:

**Do we ignore missing values?**

pygeos/shapely is mixed on this. `intersection` does not ignore missing values, but `intersection_all` does. That isn't right! **I think the struggle that @brendan-ward  described in #1501 is caused by this design flaw (my bad...)**

- If we want to ignore missing values, then we need a separate ufunc implementation.

I think we should aim for making this a user-defined option. The `skip_na` version has the minimum impact on the existing API.

**What do we return on empty input?**

What happens on `intersection_all([])` or `intersection_all([None, None], skip_na=True)`?
This should be answered per operation. I think for all the reductions we have, we should indeed return an EMPTY for an empty slice.

**What do we do for Shapely 2.0?**

If we don't want to break the API of shapely, the existing `unary_union` the "skip_na" kwarg should default to True.

- make a new implementation for the "skip_na" version of reduction functions
- default "skip_na" to True

**Comment by jorisvandenbossche** [comment]
> **Do we ignore missing values?**
> 
> pygeos/shapely is mixed on this. `intersection` does not ignore missing values, but `intersection_all` does. That isn't right!

I think this difference is actually fine (see also my earlier comment about this at https://github.com/shapely/shapely/pull/1501#issuecomment-1231587187), and your final conclusion to have skipna=True also keeps that difference. 
But it is certainly true that because of this difference in behaviour, implementing both using the same ufunc caused the difficulties (and inconsistencies) we are running into.

I was at some point thinking we could use the `where` keyword of ufuncs to have this None-skipping behaviour for the reducing version (eg `shapely.lib.intersection.reduce(arr, where=shapely.is_geometry(arr))`). But the problem with this is that in that case, numpy requires to specify an `initial` value. And that is not possible for something like intersection (since indeed you can't use an empty geometry for this, since that would otherwise only give empties as a result; basically you would need something like an "infinite" geometry covering the whole space ..).

> **What do we return on empty input?**
> 
> What happens on `intersection_all([])` or `intersection_all([None, None], skip_na=True)`? This should be answered per operation. I think for all the reductions we have, we should indeed return an EMPTY for an empty slice.

For `union`, an empty geometry certainly makes sense for the empty slice. However, I am not 100% sure empty is the best option for others such as `intersection`. 
In general, for a reduction operation, I think it is nice that it is a "splittable" operation, i.e. that it can be done in a piece-wise manner and still result the same (eg `sum([a, b, c, d]) == sum([sum([a, b]), sum([c, d]))`). If for intersection an all-None slice would result in an empty geometry, that equivalence would not hold (the use case I am thinking of is implementing intersection_all in a parallel way, as mentioned above https://github.com/shapely/shapely/issues/1332#issuecomment-1223567525). 
(of course, also for numeric data this depends on the actual reduction whether that works or not; for example for sum or product that works, but not for a mean)

**Comment by jorisvandenbossche** [comment]
For `unary_union`, the 1.8 behaviour was restored in #1553, and the other reducers were updated in https://github.com/shapely/shapely/pull/1562, so I think this can be closed.
