### ISSUE TITLE
Polylabel point falls outside of the polygon

### ISSUE THREAD

**Issue by radkevich-maria** [shapely/shapely#1383]
## Please note

I'm trying to find visual center of the polygon but I receive the point outside of my polygon using shapely.ops.polylabel.

## Expected behavior and actual behavior.

I receive the point POINT (-122.4064116266324 37.80229155607691) when it should be ~ POINT (-122.4057, 37.8029).

Actual behavior:

<img width="902" alt="Screenshot 2022-05-05 at 12 52 53" src="https://user-images.githubusercontent.com/59082268/166900525-0e8485bb-7438-4d81-89ae-39e9d5cf4b8d.png">

Expected behavior:

<img width="922" alt="Screenshot 2022-05-05 at 12 53 22" src="https://user-images.githubusercontent.com/59082268/166900625-07d1766a-9fbf-4e24-8f56-cb1c21b60398.png">

## Steps to reproduce the problem.

```
from shapely.geometry import Polygon
from shapely.ops import polylabel


polygon = Polygon([
              (-122.40941047668457,
              37.803324714248184),
              (-122.4094319343567,
              37.8026635004523),
              (-122.40610599517822,
              37.80262959189296),(-122.40602016448975,
              37.800188134708165),
              (-122.40488290786743,
              37.800222044388384),
              (-122.40507602691649,
              37.80346034711567),
              (-122.40941047668457,
              37.803324714248184)
            ])

point = polylabel(polygon, tolerance=1)

print(point)

```
## Operating system
Mac OS V 12.3.1

## Shapely version and provenance
shapely==1.7.1
 from https://pypi.python.org/pypi/Shapely

**Comment by jorisvandenbossche** [comment]
@radkevich-maria I think this is due to the value of 1.0 set for `tolerance`. Because this value is large relative to the unit of your coordinates (which are in degrees and not meters), I think the result is just the starting point the algorithm used, which is the centroid:

```
In [25]: print(polygon.centroid)
POINT (-122.40641162663243 37.80229155607691)
```

If you use a small value, it will actually find a different point, although still not the one you expected:

```
In [28]: point = polylabel(polygon, tolerance=0)

In [29]: print(point)
POINT (-122.40547825938724 37.80076643074435)
```

This is a point in the lower side of the polygon, and I suppose that is because there the "width" of the polygon is the largest:

![fig](https://user-images.githubusercontent.com/1020496/167097218-f5ccc861-e7e6-49c3-a11c-20591e096769.png)

**Comment by radkevich-maria** [comment]
It works but I expect that the visual center should be at POINT (-122.4057, 37.8029). 
@jorisvandenbossche thank you for the response!

**Comment by radkevich-maria** [comment]
@jorisvandenbossche Do you have plans to update algorithm to guarantee taht a polylabel point falls in a polygon at every level of tolerance?
