### ISSUE TITLE
shapely 1.8.2 pyinstaller build on mac: AttributeError: 'NoneType' object has no attribute 'GEOSversion'

### ISSUE THREAD

**Issue by emlys** [shapely/shapely#1385]
Sorry if this is the wrong place - I am posting here because while it's only an issue for conda users, it is a bug in the shapely source and not the conda feedstock.

## Expected behavior and actual behavior.
Expect importing `shapely.wkt` to work in a pyinstaller app built in a conda environment, but instead it raises `AttributeError: 'NoneType' object has no attribute 'GEOSversion'`

## Steps to reproduce the problem.
```
$ conda create -n test pyinstaller shapely==1.8.2 && conda activate test
$ echo "import shapely.wkt" > script.py
$ pyinstaller script.py
$ dist/script/script
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    import shapely.wkt
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "shapely/wkt.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "shapely/geos.py", line 252, in <module>
  File "shapely/geos.py", line 242, in _geos_version
AttributeError: 'NoneType' object has no attribute 'GEOSversion'
[9218] Failed to execute script 'script' due to unhandled exception!
```
The problem seems to be in this conditional:
https://github.com/shapely/shapely/blob/15e748b658f9ff9cf51bfb3fd958ded866478ec4/shapely/geos.py#L131-L147
In a pyinstaller frozen environment, `_lgeos` is never set and `alt_paths` are unused.

If you install shapely with `pip` instead of `conda`, there is no error because the dylib glob path matches and `_lgeos` gets defined:
https://github.com/shapely/shapely/blob/15e748b658f9ff9cf51bfb3fd958ded866478ec4/shapely/geos.py#L117-L129

## Operating system
MacOS 10.15.7

## Shapely version and provenance
1.8.2 from conda-forge

**Comment by mwtoews** [comment]
Same issue with conda on Linux... but not Windows (it works!?)

**Comment by zjlamtt** [comment]
it seems that you lose a package:shapely.lib
I try to put this into the dist dictionary and solve this problem

**Comment by emlys** [comment]
I'd be happy to submit a pull request for this, if that would be helpful.

**Comment by jorisvandenbossche** [comment]
A PR is certainly welcome (that will make it easier to see what change is needed, I think none of the maintainers is very familiar with pyinstaller)

**Comment by jemissik** [comment]
Just wondering if there is any update about this. I have a project where I'm currently having to pin shapely<1.8.2 because of this. Thanks!!

**Comment by ykern** [comment]
I had the same error building a bundle with pyinstaller from a conda environment on Linux using:
- Ubuntu 20.04.5 LTS
- shapely=1.7.1
- pyinstaller=3.4
- python3.6

Following approach might be possible to adjust to work on other platforms such as Mac or Windows as well.

## geos.py 
Checking out the `geos.py` file of the shapely package showed that there is already a routine for conda env and frozen states, see a copy of that part below for the version I am using:
```python
if sys.platform.startswith('linux'):
    # Test to see if we have a wheel repaired by 'auditwheel' containing its
    # own libgeos_c
    geos_whl_so = glob.glob(os.path.abspath(os.path.join(os.path.dirname(
        __file__), '.libs/libgeos_c-*.so.*')))
    if len(geos_whl_so) == 1:
        _lgeos = CDLL(geos_whl_so[0])
        LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
    elif hasattr(sys, 'frozen'):
        geos_pyinstaller_so = glob.glob(os.path.join(sys.prefix, 'libgeos_c-*.so.*'))
        if len(geos_pyinstaller_so) == 1:
            _lgeos = CDLL(geos_pyinstaller_so[0])
            LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
    elif os.getenv('CONDA_PREFIX', ''):
        # conda package.
        _lgeos = CDLL(os.path.join(sys.prefix, 'lib', 'libgeos_c.so'))
```

The conda statement is pointing to `libeos_c.so` which is correctly found and bundled into the target directory of the pyinstaller bundle. However, when importing shapely while in bundle world the `frozen` statement runs trying to locate the library with the name `libgeos_c-*.so.*`. This however does not get created automatically during the bundling via PyInstaller.

## PyInstaller hook for shapely
Hence, I wrote a custom hook for PyInstaller for this case. It makes sure to include the library in the target bundle so that it can be found by shapely there. 
```python
import sys
import os
import glob

if os.getenv('CONDA_PREFIX', ''):
	# path to general lib directory
	LIB_DIR = os.path.join(sys.prefix, 'lib')
	
	# check if geos frozen lib name is existent
	# at least with PyInstaller==3.4 it otherwise does not get created 
	if not glob.glob(os.path.join(LIB_DIR, 'libgeos_c-*.so.*')):
		# otherwise create a new symlink to be copied to the frozen target
		# conda package. (from shapely.geos source code)
		LIB_FILE_NAME = 'libgeos_c.so'

		# create symlink that shapely package can locate when in frozen state
		LIB_SYM_PATH = os.path.join(LIB_DIR, 'libgeos_c-1.so.1')
		command = f'ln -sf {LIB_FILE_NAME} {LIB_SYM_PATH}'
		print(f"Created symlink {LIB_SYM_PATH} -> {LIB_FILE_NAME} and added to target.")

		os.system(command)
	else:
		# if the library can already be found make sure it still gets included
		# when bundling
		LIB_SYM_PATH = glob.glob(os.path.join(LIB_DIR, 'libgeos_c-*.so.*'))[0]

	# pass path of library to pyinstaller variable binaries [(source,target)]
	binaries = [(LIB_SYM_PATH, '.')]
```
Saving above code as `hook-shapely.py` into the hooks folder of PyInstaller executes the script when importing shapely somewhere in a script. In Linux the hooks directory could be retrieved by the following terminal commands:
```shell
HOOK_PATH=$(python -c "import PyInstaller.hooks; print(PyInstaller.hooks.__file__)")
SHELL_PATH="$(dirname "$BASH_SOURCE")"
```

## Summary
This hook is what works on Linux and with some small changes might solve similar issues on other platforms. Ideally, a more complete version would be suggested to the PyInstaller team to include in their next version, but I thought I'll still post here in case that is helpful for somebody.

**Comment by emlys** [comment]
I think this has been fixed. https://github.com/shapely/shapely/issues/1526 looks like a duplicate of this issue.

**Comment by jorisvandenbossche** [comment]
In any case, everything that is mentioned here is also specific to Shapely <= 1.8, since starting with 2.0 the core library has been fully refactored.
