### ISSUE TITLE
Finalizing the STRtree interface

### ISSUE THREAD

**Issue by jorisvandenbossche** [shapely/shapely#1386]
For 1.8.0, we had quite some discussion in https://github.com/shapely/shapely/pull/1064 (and in https://github.com/shapely/shapely/pull/1094 and https://github.com/shapely/shapely/pull/1112), about the exact API we wanted for STRtree. In the end we settled on adding `query_items()` and `query_geoms` methods (in addition to `query`) instead of adding a keyword (like `return_geometries=True/False`) in `query()`. https://github.com/shapely/shapely/pull/1112 also added the functionality to pass custom items to the the `STRtree(.., items=..)` constructor.

But in https://github.com/shapely/shapely/pull/1251, where I merged the pygeos functionality with this Shapely interface, we had again some discussion about this, indicating that it might not yet be fully resolved. 

One of the discussion points is the usage of the term "items" (https://github.com/shapely/shapely/pull/1251#issuecomment-1051407542). While the method is called `query_items()`, I used "index" in the update of the docstring. 

> Return the index (or stored item) of all geometries in the tree
> with extents that intersect the envelope of the input geometry.
>
> The returned items may be identified by an integer index (default) or
> arbitrary item values (optional) if those are provided when
> constructing the tree.

But this triggered some comments about it (eg https://github.com/shapely/shapely/pull/1251#discussion_r795242461 or https://github.com/shapely/shapely/pull/1251#discussion_r795242032). While I think we can certainly get agreement on how to understand the default behaviour, it might point to the fact that the API is not yet really ideal (also given the fact that we have a hard time to clearly / succinctly explain this in the documentation).

Some other issues with the current naming in the API:

- The default is to return integer indices (if the user only provided geometries to the STRtree constructor), but the method is actually called `query_items()` using "items".  
 (I personally _think_ that most people will never pass explicit items, but will rather use the indices) 
- The `query_bulk()` method _only_ returns integer indices, and never items (even if the user passed those in the constructor), creating some more inconsistency. And the same applies to `nearest_all`. 
  (The reason for this is that this methods takes an array of query geometries as input, and so returns indices into both the tree and input geometries. Alternatively, we could require that you pass `items` as well to the `query_bulk` method, but this would further complicate this method)

---

So possible outcomes:

- Decide we are fine with how it is now, and maybe only tweak the docstring a bit further.
- Reconsider the ability to pass custom items, to avoid the dichotomy between "items" and "indices" (and it easy to mimic this as a user). 
- Reconsider the full API (i.e. the different options mentioned in https://github.com/shapely/shapely/pull/1064#issue-785861351: a keyword, different methods, different classes)

cc @sgillies @caspervdw @brendan-ward @mwtoews

**Comment by brendan-ward** [comment]
> I personally think that most people will never pass explicit items, but will rather use the indices

This is my hunch as well.  And for the rare cases where the user needs to relate the indices back to custom items, they can very easily implement this on their end.  If we indeed agree that this is an edge case that should move back to the user side instead of within shapely, then we should deprecate use of custom items.

> Reconsider the ability to pass custom items

My vote would be to remove custom items, and instead provide an easy example.  This will simplify the API and make it easier to clearly document and reason about.

**Comment by sharon-br** [comment]
I must say I use the custom items a lot, mainly for creating a map between the polygon and the actual data I want to retrieve.
My primary use case is as follows:
I store apartments data, each apartment is represented by a name and polygon.
Then, I want to query for the nearest apartment name to a specific point.
Then I create a tree with the polygons and the names as the custom items.

This is an easy solution because creating a dictionary from polygon to name is not possible since Polygon is not a hashable object.
Of course, this can be solved easily in other ways but I feel it is much more elegant this way.

**Comment by brendan-ward** [comment]
If you start with numpy arrays (we coerce to them internally), then this should be a one-line change:

(untested)

```Python
polygons = numpy.array([...geoms...])
names = numpy.array([...names...])

# storing items
tree = shapely.STRtree(polygons, names)
result_names = tree.query(some_polygon)

# using indices
tree = shapely.STRtree(polygons)
index = tree.query(some_polygon)
result_names = names.take(index)

# and if you need the polygons back out too
result_polygons = polygons.take(index)
```

If your inputs are not yet numpy arrays, only another 2 lines would be required to convert to those, and no additional performance impact since inputs are coerced to those anyway.

This seems like something where we can just provide an example, but more straightforward API that is consistent with the other tree functions (only working in indexes).

**Comment by jorisvandenbossche** [comment]
@sharon-br thanks a lot for the feedback! Would you be able to share a small code snippet that illustrates how you use the current API? (in case it deviates from the examples that Brendan and I gave)

Similarly, if you start from a python dictionary, it's only a small difference:

```python
from shapely.geometry import box, Point
from shapely.strtree import STRtree

# a dictionary with keys: geometries
data = {"p1": box(0, 0, 1, 1), "p2": box(1, 1, 2, 2)}

point = Point(0.5, 0.5)

# OPTION 1: storing the keys as custom items
tree1 = STRtree(data.values(), items=list(data.keys()))
tree1.nearest_item(point)
# 'p1'

# OPTON 2: storing only the geometries
keys_list = list(data.keys())
tree2 = STRtree(data.values())
tree2.nearest_item(point)
# 0
keys_list[tree2.nearest_item(point)]
# 'p1'
```

**Comment by sharon-br** [comment]
@jorisvandenbossche @brendan-ward There is no doubt you are both right and have a valid and good alternative to the use case I presented.
All I'm saying is that it is a nice interface since it allows to ditch the reference to the original data and avoid keeping another reference to the items for later retrieval.

In my codebase the usage looks something as follows:
```
class RoomChecker:
    def __init__(self, room_objects: list[RoomObject]):
        self._tree = STRtree(geoms=(room.polygon for room in room_objects), items=room_objects)
        # No need to keep rooms_objects

    def find_matching_rooms(self, point) -> list[RoomObject]:
      return self._tree.query_items(point)
```

**Comment by jorisvandenbossche** [comment]
One other option could be to have separate methods for indices vs items. 
For example, the `query_items` could keep working with custom items, but would raise an error if you didn't specify such items when constructing the strtree. And then eg the `query` method could then return indices (and `query_geoms` for returning geometries).

**Comment by brendan-ward** [comment]
Note: I have a forthcoming PR that refactors the base `STRtree` class to use indices exclusively for all operations, including examples of working with custom items and geometries.  We can then see if the examples are adequate to avoid subclassing it to provide handling of custom items or a geometry-specific class.

At the moment I'm also entertaining the notion of collapsing `query()` and `query_bulk()` into the same function (since we've struggled with naming), so that the results depend on whether or not the input geomety is scalar or an array (just like `nearest()` / `nearest_all()`).  I think this would be a good move for consistency.  This would allow us to bring the surface area of the API down (and underlying implementation in C could collapse to a single function too).  Figured as long as we're making breaking changes, might as well break _both_ the Shapely 1.8 API _and_ the PyGEOS API.   (I use `query_bulk()` heavily, so I don't take this lightly, but it seems like a good time to revisit the overall API)

**Comment by brendan-ward** [comment]
Also thinking that maybe we can combine `nearest()` and `nearest_all()` by adding a parameter `on_equidistant="first"|"all"`; that way the parameters `max_distance` and `return_distance` are more readily available (right now limited to `nearest_all()`) since it seems a little weird to have them limited to a special case (there were reasons, but a good time to revisit).  If all parameters are left at their defaults, this will still be equivalent to `nearest()` (uses more efficient C function), but we will have to handle the case of `return_distance=True` and `on_equidistant="first"` in the `nearest_all()` C function (should be easy).

Haven't yet investigated the implications of merging `exclusive=True` between the two functions yet, but seems theoretically straightforward.

Combined with the above changes, this brings us to a pretty tidy API:
```
class STRtree
    def query(geom, predicate=None, distance=None) -> array[int] or array[2, int]

    def nearest(
        geom, exclusive=False,
        return_distance=False,
        max_distance=None, 
        on_equidistant="first") -> int or array[2, int]
```

**Comment by brendan-ward** [comment]
We haven't yet sorted out what to do with `query` / `nearest` when provided an array of query geometries instead of scalar.

For the scalar case, from above, we were thinking:

```
class STRtreeItems(STRtree):
    def query(geom) -> array[custom_items]

class STRtreeGeoms(STRtree):
    def query(geom) -> array[geom]
```

However, for the array case, the options seem less great.  Options for `STRtreeItems::query`:
1) tuple of indices of input, custom items from tree: `query(geoms)` => `(array(...input indices...), array(...tree items...))`
2) tuple of input geometries, custom items from tree: `query(geoms)` => `(array(...input geoms...), array(...tree items...))`

I don't think it makes sense to extend the API to take custom items alongside the input geometries, e.g., 
`query(geoms, input_items)` => `(array(...input items...), array(...tree items...))`; it would be better if the APIs of the derived classes for items / geometries did not add additional parameters.

Likewise for the array case for `STRtreeGeoms::query`:
1) tuple of indices of input, custom items from tree: `query(geoms)` => `(array(...input indices...), array(...tree geoms...))`
2) array of shape(2, n) of input geometries, custom items from tree: `query(geoms)` => `array([...input geoms..., ...tree geoms...])`

Option 2 doesn't seem terrible in this case, since the next thing you might want to do is a geometric operation of the pairs of input and tree geometries (e.g., intersection).

But that isn't far removed from the base class that returns indices:

```Python
>>> geoms = [Point(0, 0), Point(1, 1), Point(2, 2)]
>>> tree = STRtree(geoms)
>>> indices = tree.query([box(0, 0, 1, 1)])
>>> results = np.array([geoms.take(indices[0]), tree.geometries.take(indices[1])])
```

Note: similar options are present for `nearest` when given input geometry arrays.

Do we instead want to limit `STRtreeItems` / `STRtreeGeoms` to scalar inputs only?  If so, then these classes seem more about an easier migration path from Shapely 1.8, but provide a more limited API.  The [example above](https://github.com/shapely/shapely/issues/1386#issuecomment-1129733121) seems like it only needs the scalar case.

**Comment by mathause** [comment]
If you have different output signatures for scalar and array input this may indicate that two methods are better? Also I'd appreciate to be able to pass geometry arrays i.e. what `query_bulk` does, e.g. [regionmask/regionmask#349](https://github.com/regionmask/regionmask/pull/349/files#diff-d51d2c684a3f8cd747ac26320062f0a66d2effcc604d468e00b76b6f00b7410bR535). (But I might just misunderstand the details of the discussion).

**Comment by brendan-ward** [comment]
> different output signatures for scalar and array input this may indicate that two methods are better

we haven't been particularly consistent about it so far; `query` / `query_bulk` were originally split into 2 methods because they were pretty different (see [background discussion in PR that added query_bulk to pygeos](https://github.com/pygeos/pygeos/pull/108)).  At that time, we reflected on the precedent set by [scipy's KDTree](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.KDTree.query_ball_point.html#scipy.spatial.KDTree.query_ball_point) which provided something _roughly_ similar to returning two different output shapes depending on whether or not input was scalar or array.

In contrast, I don't belive we had as much discussion when adding [`nearest` / `nearest_all`](https://github.com/pygeos/pygeos/pull/272); those were implemented such that the shape of the outputs was determined by the shape of the inputs.

#1422 tries to bring those APIs into alignment, so that all tree methods produce an output shape that is determined by the shape of the inputs (though this may be heavy-handed and not get approval of other devs here).

It is probably a good idea for us to be consistent with the API, so if it is better to have separate methods based on scalar vs array inputs, we should do so for each of the methods.  Feedback on whether we should lump or split those is appreciated!


The point I'm getting at [above](https://github.com/shapely/shapely/issues/1386#issuecomment-1155369107) is that it isn't clear what the outputs should even be for custom items or geometries in the case of non-scalar inputs; there isn't an obvious answer.  Which then leads to questioning if the array input methods should even exist that return geometries or custom items.

We use the array inputs that return indices heavily elsewhere, so those aren't going away.  (and they are the most performant, flexible, etc etc...)

**Comment by jorisvandenbossche** [comment]
> At the moment I'm also entertaining the notion of collapsing query() and query_bulk() into the same function (since we've struggled with naming), so that the results depend on whether or not the input geomety is scalar or an array

I like that (in the middle of doing a review pass on the PR), that indeed simplifies the interface and implementation (and tests), and avoids the "bulk" naming. 

> We haven't yet sorted out what to do with `query` / `nearest` when provided an array of query geometries instead of scalar. 
> ...
> Do we instead want to limit STRtreeItems / STRtreeGeoms to scalar inputs only?

Yeah, for array inputs those cases get messy. I don't think we should have return values which consist partly of indices and partly of items/geometries (in the last PR I also kept query_bulk indices-only for that reason). 
If we add those classes, I think we should indeed keep them scalar inputs only. But IMO that's another reason to not have those sublclasses (as they can't easily give the same interface as the parent class), and based on @sgillies' comment at https://github.com/shapely/shapely/pull/1422#issuecomment-1155663696 it seems we are in agreement to focus on just the single indices-only class (so basically keeping to what you did in https://github.com/shapely/shapely/pull/1422)

**Comment by jorisvandenbossche** [comment]
With the following two PRs merged:

* https://github.com/shapely/shapely/pull/1422
* https://github.com/shapely/shapely/issues/1423 / https://github.com/shapely/shapely/pull/1428

I think we can consider this issue done for now? 

We should maybe still try to add some deprecation warnings in a Shapely 1.8.3 release?

**Comment by sgillies** [comment]
@jorisvandenbossche I created #1444 about that and assigned it to myself. Look okay to you all?

**Comment by jorisvandenbossche** [comment]
Thanks for opening those two issues. With those issues to track the remaining tasks, I think we can close this one.
