### ISSUE TITLE
Refine __repr__ to avoid duplication of geometry type label

### ISSUE THREAD

**Issue by brendan-ward** [shapely/shapely#1411]
Originally noted on #1391 

The current `__repr__` produces something like `<shapely.Point POINT (0 0)>`, which has duplication between the class name and the WKT type (except for Z types). 

One way to solve this would be to omit the first part of the WKT type from `__repr__`:
* `Point(0,0)` => `<shapely.Point (0 0)>`
* `Point(0,0,0)` => `<shapely.Point Z (0 0 0)>`
* `Point()` => `<shapely.Point EMPTY>`
* `GeometryCollection(Point(0,0,0))` => `<shapely.GeometryCollection Z (POINT Z (0 0 0))>` 

The only case where this gets a little awkard is for goemetry collections, which use the WKT all-caps type names for members, but likely not that big a deal.

**Comment by brendan-ward** [comment]
Personally, I like the `<shapely.classname ...>` convention, because it clearly signals this thing is an instance of classname, which also means that I can look up classname in the API / shapely docs to find out more about it, and also use shapely.classname() to construct instances like it.  While the all-caps WKT types have roughly the same level of searchability in the docs, I can't make a new intance via shapely.WKTTYPE() (though as you note the coordinates couldn't be used verbatim to create a new instance either).

The shapely.classname construct is also potentially useful in something like a GeoPandas GeoSeries or numpy array of geometries, whereas a list / array / GeoSeries of `[<POINT(1 2)>, <POINT(3 4)>, ...]` is perhaps less clear about what those are (though that may just be a holdover from the days of needing to distinguish between shapely objects and their associated pygeos objects in a GeoSeries).  However, for comparison, neither numpy nor pandas / GeoPandas adds the package name prefix to their `__repr__`; they only show the classname.

**Comment by jorisvandenbossche** [comment]
Yeah, I mentioned this duplication issue also tangentially in the original issue about updating the repr (https://github.com/shapely/shapely/issues/1248). It's indeed not ideal. A few quick thoughts (but without clear answers):

* I also like including the actual class name (so `shapely.classname`, now they are top-level, for the reasons Brendan mentions
* However, I also like having the full WKT, and not only part of it. Because that makes it easier to copy paste the WKT part of the repr and use it to construct the data (eg to reproduce an issue, while debugging, ..., although this of course only works for small non-truncated geometries anyway), and it also makes it clearer that it is WKT.
* Those two items above are of course in conflict if we don't want to have the duplication ..

When having something like `<shapely.Point Z (0 0 0)>`, I find this hybrid between the python class and the WKT representation also not ideal, because "Point Z" is not an actual Python class, but neither the fully correct WKT (although the shapely WKT parser doesn't care about the lower case, so it actually works to parse that).

**Comment by brendan-ward** [comment]
For debugging via WKT, the `.wkt` attribute on a geometry is pretty convenient; the untruncated WKT can get really long for a `__repr__`, so while we can truncate less, I'm not sure we should stop truncating it.

**Comment by mwtoews** [comment]
Agree that truncated WKT is best for `__repr__`, since some geometries can be absolutely massive (e.g. PostGIS has a [1GB geometry size limit](http://www.danbaston.com/posts/2016/11/28/what-is-the-maximum-size-of-a-postgis-geometry.html); shapely/GEOS probably has a much higher limit). There are `.wkt`, `.wkb_hex`, etc. output accessors. An alternative to truncation is to summarize the geometry by the number of parts, coordinates, interiors, etc. see [ST_Summary(geometry)](https://postgis.net/docs/ST_Summary.html).

As for the classname `Point` vs `POINT`, sure let's go with the titlecase form. Even if it is a slightly inconsistent hybrid with (e.g.) "Point Z" or "GeometryCollection (POINT ...)" as noted previously. I don't see why it needs to _perfectly_ represent the classname.

As for the package name prefix, I'm not sure what is best. `<Point Z (1 2 3)>` looks fine to me, and spares 8 characters. Would a `shapely.` package name prefix help resolve any confusion from anyone debugging code where many other packages are used? (e.g. [`matplotlib.patches.Polygon`](https://matplotlib.org/stable/api/_as_gen/matplotlib.patches.Polygon.html)). I can go either way on this one.

**Comment by brendan-ward** [comment]
From discussion of @jorisvandenbossche @caspervdw @sgillies @brendan-ward today, all were agreed with suggestion from @mwtoews here to use truncated WKT in angle brackets: `<POINT (0, 0)>` (with all-caps output from GEOS)

**Comment by mwtoews** [comment]
@brendan-ward I'm actually swayed by titlecase class name in the WKT now, e.g. `<Point (0 0)>`, but am indifferent on the package name prefix `.shapely`. But don't let me stop progress, as the proposed PR is a good improvement.

**Comment by brendan-ward** [comment]
I think the issue we had was that we could pass through `<...WKT...>` with no change to the WKT emitted by GEOS other than truncating and wrapping in angle brackets, whereas properly doing titlecase (for main and subgeometries) means doing a find / replace on the truncated WKT string (only doing it on the main geometry but not subgeometries that appear in the truncated version doesn't seem great).  So titlecase seems like extra overhead that wasn't strictly necessary...
