### ISSUE TITLE
New STRtree deprecation warnings in 1.8.3

### ISSUE THREAD

**Issue by sgillies** [shapely/shapely#1444]
As mentioned in #1386, 2.0 will have a different STRTree API than the one in 1.8.0. This means we're going to walk back this stated decision (from 1.8a3 https://github.com/shapely/shapely/blob/maint-1.8/CHANGES.txt#L76-L79):

> Deprecations:
> 
> The STRtree class deprecation warnings have been removed. The class in 2.0.0 will be backwards compatible with the class in 1.8.0.

And return to this (from 1.8a1 https://github.com/shapely/shapely/blob/maint-1.8/CHANGES.txt#L136-L150):

> Deprecations:
> 
> ...
> 
> The STRtree class will be entirely changed in 2.0.0. The exact future API is not yet decided, but will be decided before 1.8.0 is released.

With the difference that the 2.0 API has been decided (though small changes might be made before 2.0.0).

We will have a 1.8.3 release and it will warn, on import of shapely.strtree, that incompatible changes are coming back again in 2.0.0. The team discussed having a 1.9.0 release for the new deprecations, but decided against that. A 1.8.3 will accomplish the same thing and there is still plenty of time before 2.0.0 to adapt.

**Comment by sgillies** [comment]
Resolved by #1470.

**Comment by jorisvandenbossche** [comment]
Another idea (not convinced myself, but just putting it here, since I was wondering about it): we could also remove again the `.._items()` methods, since those were only added in 1.8.0 and will be removed again in 2.0. Or deprecate them explicitly with a more targeted, specific deprecation warning. 
Although given that those do give a somewhat compatible behaviour (returning integer indices) with 2.0, it's probably good to keep them. That could allow someone to write code that is supporting both 1.8 and 2.0 in a similar way by using `query_items` / `query` depending on the version.

We could also explicitly deprecate passing custom items, since that is something that will be removed entirely (to avoid that people would start using this new feature from 1.8 and relying on it, while they could already directly do the workaround as we now document for 2.0)

**Comment by sgillies** [comment]
> We could also explicitly deprecate passing custom items, since that is something that will be removed entirely (to avoid that people would start using this new feature from 1.8 and relying on it, while they could already directly do the workaround as we now document for 2.0)

@jorisvandenbossche yes, this makes sense to me. One more deprecation warning for 1.8.3, then.

**Comment by sgillies** [comment]
Done in 3c75483.
