### ISSUE TITLE
performance regression and future of shapely.vectorized?

### ISSUE THREAD

**Issue by mathause** [shapely/shapely#1521]
## Expected behavior and actual behavior.

I noticed that `shapely.vectorized.contains` is considerably slower (~5x) in shapely 2.0 than 1.8. Now this function may be superfluous in the new version but then maybe it should be deprecated?

(I do plan to use an STRtree but still wanted to bring it up.) 

## Steps to reproduce the problem.

```python
import shapely
import numpy as np
import shapely.geometry
import shapely.vectorized

p = shapely.geometry.box(30, 20, 60, 60)

lon = np.arange(0, 360, 1)
lat = np.arange(90, -91, -1)
LON, LAT = np.meshgrid(lon, lat)

print(shapely.__version__)
%timeit shapely.vectorized.contains(p, LON.flatten(), LAT.flatten())
```

```
1.8.2
4.76 ms ± 49.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```
```
2.0a1
25.5 ms ± 891 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

## Operating system

Linux Mint 20.3

## Shapely version and provenance

conda install

**Comment by jorisvandenbossche** [comment]
@mathause thanks for testing shapely 2.0 !

This indeed gives a slowdown. The reason is that, before, those functions were specialized to handle x/y input, while now it's a wrapper around the vectorized predicate functions that expect geometries as input. 
So the slowdown is almost entirely due to creating the temporary Point geometries from the x/y values. When profiling your snippet above, the actual contains predicate evaluation is only 6% of the total time, while all the rest is creating and descroying the points (for shapely 2.0).

When you do already have Points to start with, the top-level `contains` it's actually faster than before (just the predicate evaluation):

```
In [2]: points = shapely.points(LON.flatten(), LAT.flatten())

In [3]: shapely.prepare(p)

In [4]: %timeit shapely.contains(p, points)
2.9 ms ± 90.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

This is of course assuming you already have points to start with. 

For the case of starting with x/y values, the wrapper using the standard predicate based on geometry objects will always be slower. We certainly could in theory keep the specialized versions taking x/y values, but it's a trade-off with the maintenance effort (and assuming the majority use case will be where people already have geometries).

**Comment by jorisvandenbossche** [comment]
Looking a bit in more detail at the profile I mentioned above (if you open the figure below in a browser, it is a bit interactive):

![test_shapely2](https://user-images.githubusercontent.com/1020496/188495910-9cd0b639-53c6-4856-aa93-494092278872.svg)

We can see that actually the for a large part the slowdown is due to the _destruction_ (dealloc) of the temporary point objects. And this in itself is for a large part due to the fact that this happens on an object-by-object basis by Python (so this is not a vectorized method), and thus also initializes/destroys a GEOS context for destructing each Point object. This seems to give a lot of overhead in this case, and it is also explicitly this case of object deallocation that was mentioned in an issue about [reintroducing a global GEOS context](https://github.com/pygeos/pygeos/issues/192).

As a quick illustration, I adapted the `GeometryObject_dealloc` function in C to use a global GEOS context instead of initializing/destructing one (based on what we had before https://github.com/pygeos/pygeos/pull/113), and then tested the following snippet:

```python
import shapely
import numpy as np

arr = np.random.randn(1_000_000, 2)


def create_destruct_points(arr):
    shapely.points(arr)

%timeit create_destruct_points(arr)
```

So we are creating a million points, and directly deallocating them again. Timing this function on main vs the small patch, this gives around 300ms vs 150ms. So half of the time here is due to the GEOS context initialization/destruction inside `GeometryObject_dealloc`. 
That's probably a good reason to consider a global GEOS context again (or specifically for this method). 

cc @caspervdw

**Comment by jorisvandenbossche** [comment]
For reference, GEOS recently added functions for contains and intersects that are specialized for x/y coordinates instead of taking a geometry, and so this can exactly replace the functionality of the current `shapely.vectorized` module. I opened a PR for this -> https://github.com/shapely/shapely/pull/1548

**Comment by mathause** [comment]
Thanks a lot for the fix in #1548 - I played around with a bit and it is now super fast again. I also tried to figure out the difference between `shapely.contains_xy` and `shapely.vectorized.contains` (and which is faster) and it was confusing until I actually checked the code.

So it might be worth
- mentioning that geometries should maybe be "prepared" in the docstring of `shapely.contains_xy` (and `shapely.contains` etc.)?
- and/or mentioning `shapely.vectorized.contains` in the docstring of of `shapely.contains_xy`?
- preparing the geometries in `shapely.contains_xy`?
- deprecate `shapely.vectorized.contains`?

**Comment by jorisvandenbossche** [comment]
Good points!

> * mentioning that geometries should maybe be "prepared" in the docstring of `shapely.contains_xy` (and `shapely.contains` etc.)?

Yes, that's a good idea to mention in the docstring.

> * reparing the geometries in `shapely.contains_xy`?

Personally I would like to see that we more "aggressively" prepare the geometries for the user, instead of requiring them to do this themselves (since it generally gives such benefits). But for now for `contains_xy`/`intersects_xy` I followed the pattern we have in other places where we prepare/destroy on the fly (so not changing the "state" of the geometry).

> deprecate `shapely.vectorized.contains`?

Yes, I think that's generally the idea to do eventually (at least I would advocate for this). I didn't do that for 2.0 (so you can write code that is compatible with both 1.8 and 2.0 without warning), but we should add the deprecation for 2.1. Will open an issue for keeping track of that. 
(so given that I also wouldn't mention `shapely.vectorized.contains` from the `contains_xy` docstring)

**Comment by jorisvandenbossche** [comment]
Opened https://github.com/shapely/shapely/issues/1630 about deprecating `shapely.vectorized`

**Comment by mathause** [comment]
Yes some of my suggestions were contradictory :wink: thanks for picking them up in #1630 & 1631!
