### ISSUE TITLE
performance regression when getting coordinates of a point in shapely 2.0

### ISSUE THREAD

**Issue by Lukasz-Piekarek** [shapely/shapely#1543]
## Expected behavior and actual behavior.

I am evaluating preparing to use shapely 2.0 in the project I am working on.

Getting "z" coordinate of a Point got noticeably slower compared to 1.8.4

## Steps to reproduce the problem.

I am using Ubuntu 20.04, Python 3.9.5, Shapely 2.0a1
This is the script I used:
```
import timeit
t = timeit.timeit("p.z", setup="from shapely.geometry import Point; p=Point(1.1, 2.2, 3.3)", number=100000)
print(t)
```
I am getting such results:
Shapely 2.0a1
0.9488813580001079
Shapely 1.8.4
0.8071446829999331

## Operating system

Ubuntu 20.04

## Shapely version and provenance

Shapely 2.0a1 installed using pip 
`pip install shapely==2.0a1`
I am comparing performance with 1.8.4

**Comment by jorisvandenbossche** [comment]
@Lukasz-Piekarek thanks for the report! (and for testing shapely 2)

This is somewhat expected, see https://github.com/shapely/shapely/issues/1021 (and the other issue comment that it references) for some more background. In short, because all functions wrapping GEOS functionality are now generalized to work on arrays, that means there is a small overhead when using those functions for single objects (like is done in the attributes/methods on the Geometry objects).

In general, if the performance of this specific case matters (i.e. if you are doing this many times over), the best you can do is to see if it is possible for your specific code to "bundle" the calls and get the coordinates for many points at once (for example, if you would now call the `.z` attribute in a for loop, you can use `shapely.get_z` on a list or array of geometries to do this in one go, and then this will actually be much faster than looping in python). To what extent such code change is possible of course depends on the exact context.

**Comment by Lukasz-Piekarek** [comment]
Thank you for a quick reply.
I made a quick experiment with this script:
```
import timeit

setup = """
from shapely.geometry import Point
import numpy as np
import shapely

point = Point(0.5, 0.6, 0.7)
points = np.array([Point(0.5*i, 0.6*i, 0.7*i) for i in range(1000)])
"""

t = timeit.timeit("point.z", setup=setup, number=100000)
print("one point", t)

t = timeit.timeit("shapely.get_z(points)", setup=setup, number=100000)
print("1000 points", t)
```
I got such numbers:
```
one point 1.0721903450003083
1000 points 2.7442050670001663
```
In shapely 1.8.4 the execution time scales linearly with the number of points. 

I can see that there are potentially large gains from using vectorised approach.

**Comment by jorisvandenbossche** [comment]
> I can see that there are potentially large gains from using vectorised approach.

Yes, the above is a good example!

Going to close this issue, since we have https://github.com/shapely/shapely/issues/1021
