### ISSUE TITLE
MultiPolygon does some slow checks on construction

### ISSUE THREAD

**Issue by Lyle-Alloy** [shapely/shapely#1615]
It's me again! back with another performance issue.

MultiPolygon does some slow checks on creation (not sure if they are strictly necessary, but that's a different point), and they are done twice!

## Expected behavior and actual behavior.

Ideally, MultiPolygon() should only check `is_empty` once for each polygon passed to it, but in reality because it checks `__bool__` and `is_empty`, and `__bool__` calls `is_empty`, it effectively checks it twice.

## Steps to reproduce the problem.

I did found this while doing profiling on our code base with py-spy. Let me know if you want me to write down exactly how I did that, but here's an image from the profiling: 
<img width="1779" alt="Screen Shot 2022-11-16 at 12 32 56 PM" src="https://user-images.githubusercontent.com/66628590/202253270-918866f3-abd2-4b4b-b59f-cce95d5ff523.png">

## Operating system

MacOS

## Shapely version and provenance

`2.0b2+9.ge027985` installed from source against GEOS 3.11

**Comment by jorisvandenbossche** [comment]
Thanks for the report! That indeed can be optimized (although in this case it shouldn't be a regression compared to 1.8.x? As the same logic seems to exist in that branch)

I find it a bit surprising that `is_empty` takes up such a large part of the time, though, since I would expect this to be a cheap operation.

**Comment by Lyle-Alloy** [comment]
I think we're looking at me making a multipolygon of 250,000 tiny polygons... Maybe not the best use of the computer's time 😄

**Comment by jorisvandenbossche** [comment]
Ah, for this specific use case, you can actually (starting with 2.0) better use `shapely.multipolygons(..)` function, which will be faster because 1) it assumes you already have polygons (while MultiPolygon(..) constructor will also convert from coordinates), and 2) it doesn't remove empties from your list of polygons. 

(one could also argue that the second item is an inconsistency we should resolve .. but I think it's also good to have a fast function that just takes whatever polygons you provide and turn that into a MultiPolygon)

**Comment by Lyle-Alloy** [comment]
Yeah I like that there are "raw" methods in 2.0 that I can fall back to when I am either positive my inputs are well formed, or I am willing to take the potential bad result. 

We updated to 2.0 recently, and I'm also doing more profiling of our code now (especially around GIL usage because our code is now multithreaded!) so I'll probably keep making more issues about performance observations I have.

Also feel free to kick them back to me if you would like me to submit a PR! I've been using shapely for ~2 yrs now so I feel like I ought to contribute back at least something

-Lyle

**Comment by jorisvandenbossche** [comment]
A PR to fix the duplicate bool/is_empty check is certainly welcome!
