### ISSUE TITLE
BUG: shapely.ops.substring issue with LineString Z in shapely 2.0.0

### ISSUE THREAD

**Issue by jfulem** [shapely/shapely#1699]
I used the `shapely.ops.substring` method in my project. There was no issue in shapely `1.8.4`. Today I upgraded to shapely `2.0.0` and I'm getting an error from calling this:
```
shapely.ops.substring(trajectory, dist1, dist2)
```
where the trajectory is a `LineString` type (LINESTRING Z), it contains Z coordinates.

```
setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (14,) + inhomogeneous part
```

It looks like only X, and Y of the `start_point` and `end_point` is used in the `vertex_list` for constructing the `LineString`

I'm using:
`Ubuntu 20.04`
`shapely 2.0.0`

**Comment by jorisvandenbossche** [comment]
Would you be able to make a small reproducible example from the failure in your project? (or try to give some more details about the characteristics of this specific linestring)

Taking a small example based on the docs, this works for me using shapely 2.0.0:

```python
from shapely.geometry import LineString
from shapely.ops import substring
ls = LineString((i, 0) for i in range(6))
# <LINESTRING (0 0, 1 0, 2 0, 3 0, 4 0, 5 0)>

substring(ls, start_dist=0.5, end_dist=3.5)
# <LINESTRING (0.5 0, 1 0, 2 0, 3 0, 3.5 0)>
```

**Comment by jfulem** [comment]
Sure. I think just adding the z coordinate is enough.
```python
from shapely.geometry import LineString
from shapely.ops import substring
ls = LineString((i, 0, 0) for i in range(6))

# this fails
substring(ls, start_dist=0.5, end_dist=3.5)

```

**Comment by jorisvandenbossche** [comment]
Ah, yes, you already mentioned you have Z coordinates. Thanks!

So the `substring` function doesn't correctly create start / stop coordinates including z coordinates, but just x and y. That means that for the above example, we try to create a new LineString from a list of mixed dimension coords:

```
ipdb> coords
[(0.5, 0.0), (1.0, 0.0, 0.0), (2.0, 0.0, 0.0), (3.0, 0.0, 0.0), (3.5, 0.0)]
```

and this now started to fail with shapely 2.0 (with the exact error depending on the numpy version). While with shapely 1.8 it took the dimensionality of the first coordinate pair, and just ignored the z values of the remainding coordintes:

```
>>> print(LineString([(0.5, 0.0), (1.0, 0.0, 0.0), (2.0, 0.0, 0.0), (3.0, 0.0, 0.0), (3.5, 0.0)]))
LINESTRING (0.5 0, 1 0, 2 0, 3 0, 3.5 0)
```

We should fix this in `substring` by properly including a z coordinate if the linestring is 3D. 
And we should also improve the error message in the LineString(..) constructor to give an informative error about it (instead of the current confusing error from numpy). But the fact that it errors I would say is actually an improvement, since before it silently ignored values (but if we keep it, we should mention this in the release notes of 2.0 as a breaking change).

**Comment by songololo** [comment]
Also running into this.

Changing these lines `(end_point.x, end_point.y)` to this sort of expression `tuple(*end_point.coords)` fixes it for me.

Will submit a pull request in case this approach is agreeable.
