### ISSUE TITLE
QST: Memory size: `XY` vs `XYZ`, `Point` vs `MultiPoint`/`LineString`?  

### ISSUE THREAD

**Issue by idanmiara** [shapely/shapely#1731]
I was wondering if the underling how much memory do shapely geometries take.
Also related to : https://github.com/shapely/shapely/issues/1686#issuecomment-1366775791
Two related questions:

1. How much overhead is there for small geometries ? - Do 100 XY `Point`s take about the same memory as 1 `MultiPoint`/`LineString` with 100 points ?

2. Do geometries take about `ndim*count*sizeof(float)` ?
```
count=length(geom.coords)
ndim=geom._ndim
```
So `XYZ` geometries take about +50% space then `XY` geometries ?
If I understand correctly - currently GEOS always saves `XY` geometries as `XYZ` so `XY` and `XYZ` geometries take the same storage space (https://github.com/libgeos/geos/blob/main/src/geom/CoordinateSequence.cpp#L39)
And would be changed in future GEOS versions, now that GEOS supports `M` values:
https://github.com/libgeos/geos/pull/721
https://github.com/shapely/shapely/issues/1648 

I was trying to verify this:
```
import shapely
from numpy import NaN
from shapely.geometry import Point, LineString

assert Point(1, 2) == Point(1, 2, NaN)
assert LineString([(1, 2), (1, 3)]) == LineString([(1, 2, NaN), (1, 3, NaN)])
assert LineString([(1, 2, 10), (1, 3, NaN)]) == LineString([(1, 2, 10), (1, 3, 0)])
ls = LineString([(1, 2, 10), (1, 3, NaN)])
print(shapely.get_coordinates(ls, include_z=True))
for z in [10, NaN]:
    geoms = [Point(1, 2), Point(1, 2, z), LineString([(1, 2), (1, 3)]), LineString([(1, 2, z), (1, 3, z)]), LineString([(1, 2, z), (1, 3, z)]), LineString([(1, 2, 10), (1, 3, z)])]
    print(geoms)
    print(shapely.has_z(geoms))
```

output:
```
[[ 1.  2. 10.]
 [ 1.  3. nan]]
[<POINT (1 2)>, <POINT Z (1 2 10)>, <LINESTRING (1 2, 1 3)>, <LINESTRING Z (1 2 10, 1 3 10)>, <LINESTRING Z (1 2 10, 1 3 10)>, <LINESTRING Z (1 2 10, 1 3 10)>]
[False  True False  True  True  True]
[<POINT (1 2)>, <POINT (1 2)>, <LINESTRING (1 2, 1 3)>, <LINESTRING (1 2, 1 3)>, <LINESTRING (1 2, 1 3)>, <LINESTRING Z (1 2 10, 1 3 0)>]
[False False False False False  True]
```

## Shapely version and provenance

Shapely 2 main

**Comment by jorisvandenbossche** [comment]
> If I understand correctly - currently GEOS always saves `XY` geometries as `XYZ` so `XY` and `XYZ` geometries take the same storage space

Yes, that's correct. Quoting Dan Baston from https://github.com/libgeos/geos/pull/721#issuecomment-1306440885 (which essentially says the same as the code comment you linked to):

> Until the entire library is made to be more dimension-aware (if ever) we are still storing Z values in all cases to avoid a crash or incorrect result when accessing values by `Coordinate&`. This means that XY coordinates are stored as XYZ, and XYM coordinates are stored as XYZM

You can't _really_ check this using the Shapely python bindings or GEOS C API, though, since it's an implementation detail of the C++ library. You can of course do what you show in the code snippet, but for example `get_coordinates(.., include_z)` could in theory also fill the z dimension with NaNs if asked for and if it didn't exist. 
Although you see that XY is basically determined as Z being NaN right now, since creating geometries with explicit NaN as the z value give you 2D geometries.

> 1. How much overhead is there for small geometries ?

100 Points certainly have overhead compared to a single MultiPoint. But there 2 parts of this overhead: the Python object, and the GEOS object. 
For the python side, you can check the memory that the shapely Geometry object itself takes with `sys.getsizeof`, and this is 56 bytes (so already quite a bit more than just the coordinates of 3 x 8 bytes). This is only the memory that the PyObject struct takes, which includes a pointer to the GEOSGeometry object. How much memory overhead this object has is something to check/ask on the GEOS side.

**Comment by jorisvandenbossche** [comment]
> ..  and the GEOS object. ... How much memory overhead this object has is something to check/ask on the GEOS side.

For larger geometries, the `n_coords * 3 * sizeof(float)` will certainly be a good estimate I assume, for small geometries like Point the overhead might be more significant. Taking a quick look, a rough estimate for a Point on the GEOS side: a Point geometry stores a CoordinateSequence, a pointer to a bounding box, an integer SRID, a pointer to a factory, and a pointer to userData, and then the CoordinateSequence itself consists of a std::vector of coordinates (for a Point only 3 floats), and stores boolean flags regarding hasz/hasm and the integer strides). So I suppose it will be in the same order of magnitude as the python object overhead.

> Although you see that XY is basically determined as Z being NaN right now, since creating geometries with explicit NaN as the z value give you 2D geometries.

This actually also has changed somewhat in the latest GEOS development version (because of the earlier mentioned refactor of CoordinateSequence to support multiple dimensionalities). Running the last part of your snippet using shapely built with GEOS main:

```
In [7]: for z in [10, NaN]: 
   ...:     geoms = [Point(1, 2), Point(1, 2, z), LineString([(1, 2), (1, 3)]), LineString([(1, 2, z), (1, 3, z)]), LineString([(1, 2, z), (1, 3, z)]), LineString([(1, 2, 10), (1, 3, z)])] 
   ...:     print(geoms) 
   ...:     print(shapely.has_z(geoms)) 
   ...:                                                                                                                                                                                                            
[<POINT (1 2)>, <POINT Z (1 2 10)>, <LINESTRING (1 2, 1 3)>, <LINESTRING Z (1 2 10, 1 3 10)>, <LINESTRING Z (1 2 10, 1 3 10)>, <LINESTRING Z (1 2 10, 1 3 10)>]
[False  True False  True  True  True]
[<POINT (1 2)>, <POINT (1 2)>, <LINESTRING (1 2, 1 3)>, <LINESTRING (1 2, 1 3)>, <LINESTRING (1 2, 1 3)>, <LINESTRING Z (1 2 10, 1 3 NaN)>]
[False  True False  True  True  True]
```

So now `has_z` is the same in both cases. When constructing the geometry manually with 3 coordinate values (even though the third is a NaN) now keeps track of that it was created as a 3D geometry:

```python
>>> import shapely
>>> from numpy import NaN
>>> p = shapely.Point(1, 2, NaN)
>>> p.has_z 
True
>>> shapely.get_coordinate_dimension(p)
3
>>> p
<POINT (1 2)>
```

But the WKT representation doesn't reflect that and still prints it as 2D, which seems an inconsistency to report to GEOS.

**Comment by idanmiara** [comment]
@jorisvandenbossche Thanks very much for the detailed explanation!

I've noticed another something weird: `print(LineString([(1, 2, 10), (1, 3, NaN)]))` outputs: `LINESTRING Z (1 2 10, 1 3 0)`
Note the NaN that was replaced by 0. Is this the intended behavior of the `wkt` representation ?

**Comment by jorisvandenbossche** [comment]
> Note the NaN that was replaced by 0. Is this the intended behavior of the wkt representation ?

That also seems to be dependent on the GEOS version. With the latest GEOS main branch, it now prints NaN:

```
In [25]: shapely.LineString([(1, 2, 10), (1, 3, NaN)])
Out[25]: <LINESTRING Z (1 2 10, 1 3 NaN)>
```
