### ISSUE TITLE
Multithreading STR Tree Query

### ISSUE THREAD

**Issue by tedik123** [shapely/shapely#1799]
I have a large tree and I would like to run multiple threads to query the tree (no insertion or deletion) using the nearest() function but using multiple threads provides no performance boost because I assume the underlying code doesn't release the GIL like some of the other code does.

Is there any way to allow for multithreading while querying an STR tree? So processes don't have to be used.

Sorry if this isn't the right place to post this.

**Comment by brendan-ward** [comment]
The underlying code already releases the GIL in `query()` and `nearest()` where possible; there are some parts of that where it reacquires the GIL to create the output numpy arrays.

How are you splitting up `nearest()` across threads?  `nearest()` is a bit of a tricky one, in that depending on the configuration of your geometries stored in the tree (how much clustering / overlap), the algorithm may have to visit several for every input geometry - so splitting up the outer loop across trees may have less benefit.  Setting `max_distance` in `query_nearest()` might help cut down on how far out the algorithm looks for nearest geometries.

I _think_ the benefit to multithreading here is when you can partition a large _outer_ loop across threads.  i.e., trying to find the nearest geometry to each of 10,000 query geometries.  If you have a small number of query geometries but a very large tree, this doesn't benefit from multithreading that is under Shapely's control because we can't multithread the internals of GEOS to speed up searching the tree for a given query geometry.

**Comment by tedik123** [comment]
This is the code I have that splits up the work across threads. The STR tree is filled with many triangles and I'm trying to query with a Point to find the nearest triangle. I have a large amount of points and the tree is also relatively large around 600,000 triangles.
```
def find_targets_STRTree(self):
    thread_count = 4
    print("Beginning search process")
    # returns a list of roughly evenly sized dictionaries containing lists of x,y points by a name
    work_by_thread = split_dict(self.targets_by_name, thread_count)
    results = []
    with concurrent.futures.ThreadPoolExecutor(max_workers=thread_count) as executor:
        futures = []
        for i in range(thread_count):
            futures.append(executor.submit(self.str_query_thread, work_by_thread[i]))
        for future in concurrent.futures.as_completed(futures):
            print("finished")
            results.append(future.result())
    #  do more work on the results goes here


  # returns a dict filled with lists of the indices found by name
def str_query_thread(self, targets_by_name: dict):
    label_indexes = {}
    print("Searching points for targets...")
    for area_name, targets in targets_by_name.items():
        # create the initial empty array for that key
        label_indexes[area_name] = []
        for target in targets:
            target = tuple(target)
            target_found = self.str_tree.nearest(Point(target))
            if target_found:
                index = target_found
                label_indexes[area_name].append(index)
    return label_indexes
```

**Comment by jorisvandenbossche** [comment]
The `nearest()` function itself is also vectorized, so it will be more efficient if you pass an array of Points to it, instead of a single Point at a time. So if you have a large amount of Points to query, I would divide those in decent size chunks, and then call `query()` once with such a chunk in each thread. That should ensure more time is spent inside the part of query that releases the GIL.

I didn't look in detail and so it's only a guess, but one potential explanation for that you don't see any performance improvement is that the python overhead in `str_query_thread` to loop over the points, create the point, ... etc is larger than `query` call itself, and so the bottleneck is in Python code, and thus the threading won't help.
