### ISSUE TITLE
Weird result when checking if a point is inside a polygon

### ISSUE THREAD

**Issue by tianzhuqiao** [shapely/shapely#2060]
Thanks for the great project. I am using the `contains` function to check if a point is inside a polygon. It works great for most cases, but some result looks weird. 
For the following example, it will report that the point is not inside the polygon, which is apparently inside from the plot.

```python
>>> xv = [0.5,0.2,1.0,0,0.8,0.5]
>>> yv = [1.0,0.1,0.7,0.7,0.1,1]
>>> xq = 0.5
>>> yq = 0.6
>>> polygon = Polygon(list(zip(xv, yv)))
>>> polygon.contains(Point(xq, yq))
False
```
![image](https://github.com/shapely/shapely/assets/12435643/6c8f829e-17c0-4ca7-b966-a88f12821461)

## Operating system
Windows 10

## Shapely version and provenance
Ver 2.0.4 installed from PyPI using pip

**Comment by brendan-ward** [comment]
The polygon is not valid (several crossing edges), so it will not necessarily return valid predicate results:

```Python
>>> polygon.is_valid
False
```

In this case, using a zero-length buffer to extract the outer boundary will work for the predicate:

```Python
>>> polygon = polygon.buffer(0)
>>> polygon.contains(Point(xq, yq))
True
```

Unfortunately `shapely.make_valid` does not work here because of the degree of self-intersections; it drops the interior shape, and so the predicate remains false, but for different reasons:
<img width="348" alt="image" src="https://github.com/shapely/shapely/assets/3375604/325457f1-1651-4059-969b-77b4916ddc5b">

**Comment by tianzhuqiao** [comment]
Got it, it makes sense now. Thanks!
