### ISSUE TITLE
Geometries no longer hashable in Python 3

### ISSUE THREAD

**Issue by jwass** [shapely/shapely#209]
After 1bf2b40b36077ad3bc122372216e483d87a2af52 , which implements `__eq__()` for geometries, geometries are no longer hashable in Python 3. This arose from testing GeoPandas with the latest Shapely. A test case performs a DataFrame merge on the geometry column, which requires hashable values.

The relevant new info in Python 3 from https://docs.python.org/3/reference/datamodel.html#object.__hash__:
"A class that overrides `__eq__()` and does not define `__hash__()` will have its `__hash__()` implicitly set to `None`"
(compare to Python 2 docs https://docs.python.org/2/reference/datamodel.html#object.__hash__)

We could:
- Set `__hash__ = (parent class).__hash__` on any object that implements `__eq__()` to return to the old behavior. Are there any side effects if `x == y` but `hash(x) != hash(y)`?
- Argue that geometries shouldn't ever have been hashable as they are technically mutable (although I'd bet there are few applications that do this). This would make it a Pandas/GeoPandas problem (and you probably shouldn't be merging on the geometry column anyway). If so, we should explicitly set `__hash__` to `None` to backport the behavior to Python 2. And note that it will break any code that hashed geometries previously, such as using geometries as keys to a dictionary
- Make our own custom hash function for geometries that's probably some combination of the geometry type and coordinates - still has the mutability issue.
- Anything else I haven't thought of or don't know about.

I think I'd vote for the first one, but I'm not completely sold.

**Comment by danielwe** [comment]
I happened to bump into this issue today. As explained by @demosdemon, the current behavior is inconsistent. From the python docs (https://docs.python.org/3/reference/datamodel.html#object.__hash__):
> \_\_hash\_\_() should return an integer. The only required property is that objects which compare equal have the same hash value; it is advised to somehow mix together (e.g. using exclusive or) the hash values for the components of the object that also play a part in comparison of objects.

and

> If a class defines mutable objects and implements an \_\_eq\_\_() method, it should not implement \_\_hash\_\_(), since the implementation of hashable collections requires that a key’s hash value is immutable (if the object’s hash value changes, it will be in the wrong hash bucket).

Thus, shapely should either
- embrace mutablility as a property of geometries, and set `__hash__ = None` in the relevant (base) classes, or
- define geometries as immutable, and develop suitable custom hash methods.

I don't think creating custom hash methods has to be difficult. For example, the `BaseGeometry` class could perhaps get away with something like
```python
    def __hash__(self):
        return hash(tuple(self.coords))
```
while the `BaseMultipartGeometry` class could use something like
```python
    def __hash__(self):
        return hash(frozenset(self))
```
(disclaimer: I'm no hashing expert).

In addition, it would probably be a good idea to try to enforce immutability of the attributes used in the hash computation. With the examples above, the only thing that needs to be done as far as I can see is to make `coords` a read-only (getter-only) property in `BaseGeometry` and all derived classes.

Finally, note that consistent hashing can facilitate a very simple implementation of order-agnostic comparison of multipart geometries, as discussed in #194, by going via `set` (this cannot be done now, since `set` does not work correctly without consistent hash methods on the elements):
```python
    def __eq__(self, other):
        return (
            isinstance(other, self.__class__) and
            set(self) == set(other)
        )
```
Note that this comparison is also agnostic to duplicates in the multipart geometry.

**Comment by sgillies** [comment]
@danielwe @demosdemon thanks for the careful explanations. I'm convinced that `__hash__ = None` is the way to go for 1.6.0. I'd really like immutable geometries, but that's a feature for a Shapely 2.0.
