### ISSUE TITLE
`minimum_rotated_rectangle` docs have incorrect example for `oriented_envelope`

### ISSUE THREAD

**Issue by johnthagen** [shapely/shapely#2096]
If you visit the `shapely.minimum_rotated_rectangle` page of the docs:

- https://shapely.readthedocs.io/en/2.0.5/reference/shapely.minimum_rotated_rectangle.html

The examples reference is incorrect and refers to `oriented_envelope`.

```py
from shapely import GeometryCollection, LineString, MultiPoint, Point, Polygon
oriented_envelope(MultiPoint([(0, 0), (10, 0), (10, 10)])).normalize()
<POLYGON ((0 0, 10 10, 15 5, 5 -5, 0 0))>
oriented_envelope(LineString([(1, 1), (5, 1), (10, 10)])).normalize()
<POLYGON ((1 1, 10 10, 12 8, 3 -1, 1 1))>
oriented_envelope(Polygon([(1, 1), (15, 1), (5, 10), (1, 1)])).normalize()
<POLYGON ((1 1, 1 10, 15 10, 15 1, 1 1))>
oriented_envelope(LineString([(1, 1), (10, 1)])).normalize()
<LINESTRING (1 1, 10 1)>
oriented_envelope(Point(2, 2))
<POINT (2 2)>
oriented_envelope(GeometryCollection([]))
<POLYGON EMPTY>
```

<img width="710" alt="Screenshot 2024-07-25 at 1 26 22 PM" src="https://github.com/user-attachments/assets/d9a8410a-dead-4097-9f53-72cae3797ce6">

**Comment by johnthagen** [comment]
Oh, after digging into the Shapely code, I see that  `minimum_rotated_rectangle` is an alias

```py
minimum_rotated_rectangle = oriented_envelope
```

This still seems a bit surprising for the docs to show another function though? Maybe it is because the docs are auto-generated and following a reference to same place?

**Comment by jorisvandenbossche** [comment]
> This still seems a bit surprising for the docs to show another function though? Maybe it is because the docs are auto-generated and following a reference to same place?

The actual reason is because of `minimum_rotated_rectangle = oriented_envelope`, i.e. `minimum_rotated_rectangle` is simply an alias and therefore has the exact same definition and docstring as `oriented_envelope`.

Adding some complexity or duplication to ensure the docstring of `minimum_rotated_rectangle` uses the correct name seems not worth it IMO, but we should definity mention `minimum_rotated_rectangle` as being an alias in the shared docstring. 
In that case the docstring of `minimum_rotated_rectangle` will still use `oriented_envelope` in the examples, but will mention that `oriented_envelope` is an alias. That might be sufficient?

**Comment by johnthagen** [comment]
> In that case the docstring of minimum_rotated_rectangle will still use oriented_envelope in the examples, but will mention that oriented_envelope is an alias.

@jorisvandenbossche That sounds like a great idea to me.

**Comment by jorisvandenbossche** [comment]
This was done in https://github.com/shapely/shapely/pull/2104, so closing this issue
