### ISSUE TITLE
from_wkt and from_wkb crash on MULTISURFACE input

### ISSUE THREAD

**Issue by theroggy** [shapely/shapely#2159]
GEOS 3.13 introduced basic support for CURVE/SURFACE geometries, mainly to be able to parse them from WKB and WKT. However, `shapely.from_wkt` and `shapely.from_wkb` seem to crash on this type of input.

Noticed in a crashing test in pyogrio: https://github.com/geopandas/pyogrio/issues/478

Testing GEOS directly using `geosop` doesn't seem to trigger the problem (see issue above)?

I've had a quick look at the shapely code and don't immediately see where it can go wrong specifically on the curve types... but I'm not very familiar with the code, so probably missed something.

I also wonder what is going to happen if other shapely functions are going to be called on these geometries... but that's to be seen after this is solved :-)

Script to reproduce:

``` python
import shapely

wkt = "MULTISURFACE (CURVEPOLYGON ((-95.29698763468994 63.36578165250125, -94.5991423640996 53.06992070409323, -73.7073995758013 60.149472648492385, -95.29698763468994 63.36578165250125)))"
print(shapely.from_wkt(wkt))
print("here")
```

**Comment by brendan-ward** [comment]
Also fails for some of the WKBs in the GEOS test suite for nonlinear WKBs added in [geos #1106](https://github.com/libgeos/geos/pull/1106).

It looks like the actual read operation using GEOS is working properly and we're failing downstream of that.  We have a variety of checks against the type ID of the geometry throughout the codebase, and since these type IDs are effectively new to Shapely (GEOS <3.13 they were rejected by GEOS on read from WKT / WKB) it is possible that we are falling through a conditional statement somewhere and trying to do an unsupported operation on a nonlinear type.  Investigating now.

A short term fix may be to detect nonlinear types immediately after read from WKT / WKB and immediately convert them to their linear counterparts until better support for nonlinear types is added throughout Shapely.
