### ISSUE TITLE
parallel_offset 'right' return wrong value

### ISSUE THREAD

**Issue by lichunr** [shapely/shapely#785]
## Please note

If you are reporting an installation or module import issue, please note that
this project only accepts reports about problems with packages downloaded from
the Python Package Index. Conda users should take issues to one of the
following trackers:

- https://github.com/ContinuumIO/anaconda-issues/issues
- https://github.com/conda-forge/shapely-feedstock

## Expected behavior and actual behavior.
 create a LineString, and parallel_offset to right by 1
l = LineString([(0, 0), (0, 2)])
l = l.parallel_offset(1, 'right')
print(l) # display LINESTRING (1 2, 1 0)
l = l.parallel_offset(1, 'right')
print(l) # display LINESTRING (0 0, 0 2)

expected value: LINESTRING(2 0, 2 2)

(parallel_offset 'left' has no such issue)

## Steps to reproduce the problem.

(like shown above)

## Operating system

Mac OS X 10.15 Catalina . (also on windows 10)

## Shapely version and provenance

1.6b4 installed from PyPI using pip
geos 3.8 (also the same on geos 3.7.3)

**Comment by LostFan123** [comment]
This happens because the right offset changes the orientation of the `LineString`. I don't know if this behavior is intended or not, but it would be good to document it because it confused me as well when I first encountered it.

**Comment by lichunr** [comment]
@LostFan123 agree the change of orientation, though 'left' has no such issue...

**Comment by Jeremiah-England** [comment]
It always reverses right side offsets but not left side offsets. There's [a mention of it in the change log](https://shapely.readthedocs.io/en/latest/project.html#id8) because of issue #284. 

The change log states that the right side reversal was 'noted' but I can't find it in the docs. It should probably be put in.

**Comment by jorisvandenbossche** [comment]
The change in orientation, although documented on in our docs, was an implementation detail of GEOS. And starting with GEOS >= 3.11, the implementation will now always try to preserve the orientation, instead of changing it. 

This has been clarified in the docs in https://github.com/shapely/shapely/pull/1537
